//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8825
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Subscription.schemas {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("SubscriptionDS")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class SubscriptionDS : global::System.Data.DataSet {
        
        private suscriptionDataTable tablesuscription;
        
        private operator_subscriptionDataTable tableoperator_subscription;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public SubscriptionDS() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected SubscriptionDS(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["suscription"] != null)) {
                    base.Tables.Add(new suscriptionDataTable(ds.Tables["suscription"]));
                }
                if ((ds.Tables["operator_subscription"] != null)) {
                    base.Tables.Add(new operator_subscriptionDataTable(ds.Tables["operator_subscription"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public suscriptionDataTable suscription {
            get {
                return this.tablesuscription;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public operator_subscriptionDataTable operator_subscription {
            get {
                return this.tableoperator_subscription;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override global::System.Data.DataSet Clone() {
            SubscriptionDS cln = ((SubscriptionDS)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["suscription"] != null)) {
                    base.Tables.Add(new suscriptionDataTable(ds.Tables["suscription"]));
                }
                if ((ds.Tables["operator_subscription"] != null)) {
                    base.Tables.Add(new operator_subscriptionDataTable(ds.Tables["operator_subscription"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars(bool initTable) {
            this.tablesuscription = ((suscriptionDataTable)(base.Tables["suscription"]));
            if ((initTable == true)) {
                if ((this.tablesuscription != null)) {
                    this.tablesuscription.InitVars();
                }
            }
            this.tableoperator_subscription = ((operator_subscriptionDataTable)(base.Tables["operator_subscription"]));
            if ((initTable == true)) {
                if ((this.tableoperator_subscription != null)) {
                    this.tableoperator_subscription.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitClass() {
            this.DataSetName = "SubscriptionDS";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/DavidDevidDS.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tablesuscription = new suscriptionDataTable();
            base.Tables.Add(this.tablesuscription);
            this.tableoperator_subscription = new operator_subscriptionDataTable();
            base.Tables.Add(this.tableoperator_subscription);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private bool ShouldSerializesuscription() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private bool ShouldSerializeoperator_subscription() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            SubscriptionDS ds = new SubscriptionDS();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        public delegate void suscriptionRowChangeEventHandler(object sender, suscriptionRowChangeEvent e);
        
        public delegate void operator_subscriptionRowChangeEventHandler(object sender, operator_subscriptionRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class suscriptionDataTable : global::System.Data.TypedTableBase<suscriptionRow> {
            
            private global::System.Data.DataColumn columnsuscription_id;
            
            private global::System.Data.DataColumn columnpackage_id;
            
            private global::System.Data.DataColumn columnmsisdn;
            
            private global::System.Data.DataColumn columnlast_charge_order_no;
            
            private global::System.Data.DataColumn columnlast_charge_msg_date;
            
            private global::System.Data.DataColumn columnlast_charge_date;
            
            private global::System.Data.DataColumn columnis_new;
            
            private global::System.Data.DataColumn columnactive;
            
            private global::System.Data.DataColumn columnregistered_on;
            
            private global::System.Data.DataColumn columnunregistered_on;
            
            private global::System.Data.DataColumn columnlast_attempt_dispatch_no;
            
            private global::System.Data.DataColumn columnlast_attempt_no;
            
            private global::System.Data.DataColumn columnlast_attempt_date;
            
            private global::System.Data.DataColumn columnlast_attempt_weekly_failed;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public suscriptionDataTable() {
                this.TableName = "suscription";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal suscriptionDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected suscriptionDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn suscription_idColumn {
                get {
                    return this.columnsuscription_id;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn package_idColumn {
                get {
                    return this.columnpackage_id;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn msisdnColumn {
                get {
                    return this.columnmsisdn;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn last_charge_order_noColumn {
                get {
                    return this.columnlast_charge_order_no;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn last_charge_msg_dateColumn {
                get {
                    return this.columnlast_charge_msg_date;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn last_charge_dateColumn {
                get {
                    return this.columnlast_charge_date;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn is_newColumn {
                get {
                    return this.columnis_new;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn activeColumn {
                get {
                    return this.columnactive;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn registered_onColumn {
                get {
                    return this.columnregistered_on;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn unregistered_onColumn {
                get {
                    return this.columnunregistered_on;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn last_attempt_dispatch_noColumn {
                get {
                    return this.columnlast_attempt_dispatch_no;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn last_attempt_noColumn {
                get {
                    return this.columnlast_attempt_no;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn last_attempt_dateColumn {
                get {
                    return this.columnlast_attempt_date;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn last_attempt_weekly_failedColumn {
                get {
                    return this.columnlast_attempt_weekly_failed;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public suscriptionRow this[int index] {
                get {
                    return ((suscriptionRow)(this.Rows[index]));
                }
            }
            
            public event suscriptionRowChangeEventHandler suscriptionRowChanging;
            
            public event suscriptionRowChangeEventHandler suscriptionRowChanged;
            
            public event suscriptionRowChangeEventHandler suscriptionRowDeleting;
            
            public event suscriptionRowChangeEventHandler suscriptionRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void AddsuscriptionRow(suscriptionRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public suscriptionRow AddsuscriptionRow(long suscription_id, int package_id, string msisdn, short last_charge_order_no, System.DateTime last_charge_msg_date, System.DateTime last_charge_date, string is_new, string active, System.DateTime registered_on, System.DateTime unregistered_on, short last_attempt_dispatch_no, short last_attempt_no, System.DateTime last_attempt_date, string last_attempt_weekly_failed) {
                suscriptionRow rowsuscriptionRow = ((suscriptionRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        suscription_id,
                        package_id,
                        msisdn,
                        last_charge_order_no,
                        last_charge_msg_date,
                        last_charge_date,
                        is_new,
                        active,
                        registered_on,
                        unregistered_on,
                        last_attempt_dispatch_no,
                        last_attempt_no,
                        last_attempt_date,
                        last_attempt_weekly_failed};
                rowsuscriptionRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowsuscriptionRow);
                return rowsuscriptionRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public suscriptionRow FindBysuscription_id(long suscription_id) {
                return ((suscriptionRow)(this.Rows.Find(new object[] {
                            suscription_id})));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public override global::System.Data.DataTable Clone() {
                suscriptionDataTable cln = ((suscriptionDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataTable CreateInstance() {
                return new suscriptionDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal void InitVars() {
                this.columnsuscription_id = base.Columns["suscription_id"];
                this.columnpackage_id = base.Columns["package_id"];
                this.columnmsisdn = base.Columns["msisdn"];
                this.columnlast_charge_order_no = base.Columns["last_charge_order_no"];
                this.columnlast_charge_msg_date = base.Columns["last_charge_msg_date"];
                this.columnlast_charge_date = base.Columns["last_charge_date"];
                this.columnis_new = base.Columns["is_new"];
                this.columnactive = base.Columns["active"];
                this.columnregistered_on = base.Columns["registered_on"];
                this.columnunregistered_on = base.Columns["unregistered_on"];
                this.columnlast_attempt_dispatch_no = base.Columns["last_attempt_dispatch_no"];
                this.columnlast_attempt_no = base.Columns["last_attempt_no"];
                this.columnlast_attempt_date = base.Columns["last_attempt_date"];
                this.columnlast_attempt_weekly_failed = base.Columns["last_attempt_weekly_failed"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitClass() {
                this.columnsuscription_id = new global::System.Data.DataColumn("suscription_id", typeof(long), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnsuscription_id);
                this.columnpackage_id = new global::System.Data.DataColumn("package_id", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnpackage_id);
                this.columnmsisdn = new global::System.Data.DataColumn("msisdn", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnmsisdn);
                this.columnlast_charge_order_no = new global::System.Data.DataColumn("last_charge_order_no", typeof(short), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnlast_charge_order_no);
                this.columnlast_charge_msg_date = new global::System.Data.DataColumn("last_charge_msg_date", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnlast_charge_msg_date);
                this.columnlast_charge_date = new global::System.Data.DataColumn("last_charge_date", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnlast_charge_date);
                this.columnis_new = new global::System.Data.DataColumn("is_new", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnis_new);
                this.columnactive = new global::System.Data.DataColumn("active", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnactive);
                this.columnregistered_on = new global::System.Data.DataColumn("registered_on", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnregistered_on);
                this.columnunregistered_on = new global::System.Data.DataColumn("unregistered_on", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnunregistered_on);
                this.columnlast_attempt_dispatch_no = new global::System.Data.DataColumn("last_attempt_dispatch_no", typeof(short), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnlast_attempt_dispatch_no);
                this.columnlast_attempt_no = new global::System.Data.DataColumn("last_attempt_no", typeof(short), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnlast_attempt_no);
                this.columnlast_attempt_date = new global::System.Data.DataColumn("last_attempt_date", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnlast_attempt_date);
                this.columnlast_attempt_weekly_failed = new global::System.Data.DataColumn("last_attempt_weekly_failed", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnlast_attempt_weekly_failed);
                this.Constraints.Add(new global::System.Data.UniqueConstraint("Constraint1", new global::System.Data.DataColumn[] {
                                this.columnsuscription_id}, true));
                this.columnsuscription_id.AutoIncrementSeed = -1;
                this.columnsuscription_id.AutoIncrementStep = -1;
                this.columnsuscription_id.AllowDBNull = false;
                this.columnsuscription_id.Unique = true;
                this.columnmsisdn.MaxLength = 20;
                this.columnis_new.MaxLength = 1;
                this.columnactive.MaxLength = 1;
                this.columnlast_attempt_weekly_failed.MaxLength = 1;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public suscriptionRow NewsuscriptionRow() {
                return ((suscriptionRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new suscriptionRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Type GetRowType() {
                return typeof(suscriptionRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.suscriptionRowChanged != null)) {
                    this.suscriptionRowChanged(this, new suscriptionRowChangeEvent(((suscriptionRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.suscriptionRowChanging != null)) {
                    this.suscriptionRowChanging(this, new suscriptionRowChangeEvent(((suscriptionRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.suscriptionRowDeleted != null)) {
                    this.suscriptionRowDeleted(this, new suscriptionRowChangeEvent(((suscriptionRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.suscriptionRowDeleting != null)) {
                    this.suscriptionRowDeleting(this, new suscriptionRowChangeEvent(((suscriptionRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void RemovesuscriptionRow(suscriptionRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                SubscriptionDS ds = new SubscriptionDS();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "suscriptionDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class operator_subscriptionDataTable : global::System.Data.TypedTableBase<operator_subscriptionRow> {
            
            private global::System.Data.DataColumn columnoperator_suscription_id;
            
            private global::System.Data.DataColumn columnsuscription_id;
            
            private global::System.Data.DataColumn columnunregistered_by;
            
            private global::System.Data.DataColumn columnexpire_date;
            
            private global::System.Data.DataColumn columnsuscription_status;
            
            private global::System.Data.DataColumn columnrenew_status;
            
            private global::System.Data.DataColumn columncreated_on;
            
            private global::System.Data.DataColumn columnoperator_id;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public operator_subscriptionDataTable() {
                this.TableName = "operator_subscription";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal operator_subscriptionDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected operator_subscriptionDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn operator_suscription_idColumn {
                get {
                    return this.columnoperator_suscription_id;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn suscription_idColumn {
                get {
                    return this.columnsuscription_id;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn unregistered_byColumn {
                get {
                    return this.columnunregistered_by;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn expire_dateColumn {
                get {
                    return this.columnexpire_date;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn suscription_statusColumn {
                get {
                    return this.columnsuscription_status;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn renew_statusColumn {
                get {
                    return this.columnrenew_status;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn created_onColumn {
                get {
                    return this.columncreated_on;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn operator_idColumn {
                get {
                    return this.columnoperator_id;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public operator_subscriptionRow this[int index] {
                get {
                    return ((operator_subscriptionRow)(this.Rows[index]));
                }
            }
            
            public event operator_subscriptionRowChangeEventHandler operator_subscriptionRowChanging;
            
            public event operator_subscriptionRowChangeEventHandler operator_subscriptionRowChanged;
            
            public event operator_subscriptionRowChangeEventHandler operator_subscriptionRowDeleting;
            
            public event operator_subscriptionRowChangeEventHandler operator_subscriptionRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Addoperator_subscriptionRow(operator_subscriptionRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public operator_subscriptionRow Addoperator_subscriptionRow(long operator_suscription_id, long suscription_id, string unregistered_by, System.DateTime expire_date, short suscription_status, short renew_status, System.DateTime created_on, int operator_id) {
                operator_subscriptionRow rowoperator_subscriptionRow = ((operator_subscriptionRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        operator_suscription_id,
                        suscription_id,
                        unregistered_by,
                        expire_date,
                        suscription_status,
                        renew_status,
                        created_on,
                        operator_id};
                rowoperator_subscriptionRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowoperator_subscriptionRow);
                return rowoperator_subscriptionRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public override global::System.Data.DataTable Clone() {
                operator_subscriptionDataTable cln = ((operator_subscriptionDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataTable CreateInstance() {
                return new operator_subscriptionDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal void InitVars() {
                this.columnoperator_suscription_id = base.Columns["operator_suscription_id"];
                this.columnsuscription_id = base.Columns["suscription_id"];
                this.columnunregistered_by = base.Columns["unregistered_by"];
                this.columnexpire_date = base.Columns["expire_date"];
                this.columnsuscription_status = base.Columns["suscription_status"];
                this.columnrenew_status = base.Columns["renew_status"];
                this.columncreated_on = base.Columns["created_on"];
                this.columnoperator_id = base.Columns["operator_id"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitClass() {
                this.columnoperator_suscription_id = new global::System.Data.DataColumn("operator_suscription_id", typeof(long), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnoperator_suscription_id);
                this.columnsuscription_id = new global::System.Data.DataColumn("suscription_id", typeof(long), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnsuscription_id);
                this.columnunregistered_by = new global::System.Data.DataColumn("unregistered_by", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnunregistered_by);
                this.columnexpire_date = new global::System.Data.DataColumn("expire_date", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnexpire_date);
                this.columnsuscription_status = new global::System.Data.DataColumn("suscription_status", typeof(short), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnsuscription_status);
                this.columnrenew_status = new global::System.Data.DataColumn("renew_status", typeof(short), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnrenew_status);
                this.columncreated_on = new global::System.Data.DataColumn("created_on", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columncreated_on);
                this.columnoperator_id = new global::System.Data.DataColumn("operator_id", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnoperator_id);
                this.columnoperator_suscription_id.AllowDBNull = false;
                this.columnsuscription_id.AllowDBNull = false;
                this.columnunregistered_by.MaxLength = 20;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public operator_subscriptionRow Newoperator_subscriptionRow() {
                return ((operator_subscriptionRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new operator_subscriptionRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Type GetRowType() {
                return typeof(operator_subscriptionRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.operator_subscriptionRowChanged != null)) {
                    this.operator_subscriptionRowChanged(this, new operator_subscriptionRowChangeEvent(((operator_subscriptionRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.operator_subscriptionRowChanging != null)) {
                    this.operator_subscriptionRowChanging(this, new operator_subscriptionRowChangeEvent(((operator_subscriptionRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.operator_subscriptionRowDeleted != null)) {
                    this.operator_subscriptionRowDeleted(this, new operator_subscriptionRowChangeEvent(((operator_subscriptionRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.operator_subscriptionRowDeleting != null)) {
                    this.operator_subscriptionRowDeleting(this, new operator_subscriptionRowChangeEvent(((operator_subscriptionRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Removeoperator_subscriptionRow(operator_subscriptionRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                SubscriptionDS ds = new SubscriptionDS();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "operator_subscriptionDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public partial class suscriptionRow : global::System.Data.DataRow {
            
            private suscriptionDataTable tablesuscription;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal suscriptionRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tablesuscription = ((suscriptionDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public long suscription_id {
                get {
                    return ((long)(this[this.tablesuscription.suscription_idColumn]));
                }
                set {
                    this[this.tablesuscription.suscription_idColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int package_id {
                get {
                    try {
                        return ((int)(this[this.tablesuscription.package_idColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'package_id\' in table \'suscription\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablesuscription.package_idColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string msisdn {
                get {
                    try {
                        return ((string)(this[this.tablesuscription.msisdnColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'msisdn\' in table \'suscription\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablesuscription.msisdnColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public short last_charge_order_no {
                get {
                    try {
                        return ((short)(this[this.tablesuscription.last_charge_order_noColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'last_charge_order_no\' in table \'suscription\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablesuscription.last_charge_order_noColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.DateTime last_charge_msg_date {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tablesuscription.last_charge_msg_dateColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'last_charge_msg_date\' in table \'suscription\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablesuscription.last_charge_msg_dateColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.DateTime last_charge_date {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tablesuscription.last_charge_dateColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'last_charge_date\' in table \'suscription\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablesuscription.last_charge_dateColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string is_new {
                get {
                    try {
                        return ((string)(this[this.tablesuscription.is_newColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'is_new\' in table \'suscription\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablesuscription.is_newColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string active {
                get {
                    try {
                        return ((string)(this[this.tablesuscription.activeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'active\' in table \'suscription\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablesuscription.activeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.DateTime registered_on {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tablesuscription.registered_onColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'registered_on\' in table \'suscription\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablesuscription.registered_onColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.DateTime unregistered_on {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tablesuscription.unregistered_onColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'unregistered_on\' in table \'suscription\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablesuscription.unregistered_onColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public short last_attempt_dispatch_no {
                get {
                    try {
                        return ((short)(this[this.tablesuscription.last_attempt_dispatch_noColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'last_attempt_dispatch_no\' in table \'suscription\' is DBNull." +
                                "", e);
                    }
                }
                set {
                    this[this.tablesuscription.last_attempt_dispatch_noColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public short last_attempt_no {
                get {
                    try {
                        return ((short)(this[this.tablesuscription.last_attempt_noColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'last_attempt_no\' in table \'suscription\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablesuscription.last_attempt_noColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.DateTime last_attempt_date {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tablesuscription.last_attempt_dateColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'last_attempt_date\' in table \'suscription\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablesuscription.last_attempt_dateColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string last_attempt_weekly_failed {
                get {
                    try {
                        return ((string)(this[this.tablesuscription.last_attempt_weekly_failedColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'last_attempt_weekly_failed\' in table \'suscription\' is DBNul" +
                                "l.", e);
                    }
                }
                set {
                    this[this.tablesuscription.last_attempt_weekly_failedColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Ispackage_idNull() {
                return this.IsNull(this.tablesuscription.package_idColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setpackage_idNull() {
                this[this.tablesuscription.package_idColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsmsisdnNull() {
                return this.IsNull(this.tablesuscription.msisdnColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetmsisdnNull() {
                this[this.tablesuscription.msisdnColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Islast_charge_order_noNull() {
                return this.IsNull(this.tablesuscription.last_charge_order_noColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setlast_charge_order_noNull() {
                this[this.tablesuscription.last_charge_order_noColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Islast_charge_msg_dateNull() {
                return this.IsNull(this.tablesuscription.last_charge_msg_dateColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setlast_charge_msg_dateNull() {
                this[this.tablesuscription.last_charge_msg_dateColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Islast_charge_dateNull() {
                return this.IsNull(this.tablesuscription.last_charge_dateColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setlast_charge_dateNull() {
                this[this.tablesuscription.last_charge_dateColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isis_newNull() {
                return this.IsNull(this.tablesuscription.is_newColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setis_newNull() {
                this[this.tablesuscription.is_newColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsactiveNull() {
                return this.IsNull(this.tablesuscription.activeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetactiveNull() {
                this[this.tablesuscription.activeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isregistered_onNull() {
                return this.IsNull(this.tablesuscription.registered_onColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setregistered_onNull() {
                this[this.tablesuscription.registered_onColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isunregistered_onNull() {
                return this.IsNull(this.tablesuscription.unregistered_onColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setunregistered_onNull() {
                this[this.tablesuscription.unregistered_onColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Islast_attempt_dispatch_noNull() {
                return this.IsNull(this.tablesuscription.last_attempt_dispatch_noColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setlast_attempt_dispatch_noNull() {
                this[this.tablesuscription.last_attempt_dispatch_noColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Islast_attempt_noNull() {
                return this.IsNull(this.tablesuscription.last_attempt_noColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setlast_attempt_noNull() {
                this[this.tablesuscription.last_attempt_noColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Islast_attempt_dateNull() {
                return this.IsNull(this.tablesuscription.last_attempt_dateColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setlast_attempt_dateNull() {
                this[this.tablesuscription.last_attempt_dateColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Islast_attempt_weekly_failedNull() {
                return this.IsNull(this.tablesuscription.last_attempt_weekly_failedColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setlast_attempt_weekly_failedNull() {
                this[this.tablesuscription.last_attempt_weekly_failedColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public partial class operator_subscriptionRow : global::System.Data.DataRow {
            
            private operator_subscriptionDataTable tableoperator_subscription;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal operator_subscriptionRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableoperator_subscription = ((operator_subscriptionDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public long operator_suscription_id {
                get {
                    return ((long)(this[this.tableoperator_subscription.operator_suscription_idColumn]));
                }
                set {
                    this[this.tableoperator_subscription.operator_suscription_idColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public long suscription_id {
                get {
                    return ((long)(this[this.tableoperator_subscription.suscription_idColumn]));
                }
                set {
                    this[this.tableoperator_subscription.suscription_idColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string unregistered_by {
                get {
                    try {
                        return ((string)(this[this.tableoperator_subscription.unregistered_byColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'unregistered_by\' in table \'operator_subscription\' is DBNull" +
                                ".", e);
                    }
                }
                set {
                    this[this.tableoperator_subscription.unregistered_byColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.DateTime expire_date {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tableoperator_subscription.expire_dateColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'expire_date\' in table \'operator_subscription\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableoperator_subscription.expire_dateColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public short suscription_status {
                get {
                    try {
                        return ((short)(this[this.tableoperator_subscription.suscription_statusColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'suscription_status\' in table \'operator_subscription\' is DBN" +
                                "ull.", e);
                    }
                }
                set {
                    this[this.tableoperator_subscription.suscription_statusColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public short renew_status {
                get {
                    try {
                        return ((short)(this[this.tableoperator_subscription.renew_statusColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'renew_status\' in table \'operator_subscription\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableoperator_subscription.renew_statusColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.DateTime created_on {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tableoperator_subscription.created_onColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'created_on\' in table \'operator_subscription\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableoperator_subscription.created_onColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int operator_id {
                get {
                    try {
                        return ((int)(this[this.tableoperator_subscription.operator_idColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'operator_id\' in table \'operator_subscription\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableoperator_subscription.operator_idColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isunregistered_byNull() {
                return this.IsNull(this.tableoperator_subscription.unregistered_byColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setunregistered_byNull() {
                this[this.tableoperator_subscription.unregistered_byColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isexpire_dateNull() {
                return this.IsNull(this.tableoperator_subscription.expire_dateColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setexpire_dateNull() {
                this[this.tableoperator_subscription.expire_dateColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Issuscription_statusNull() {
                return this.IsNull(this.tableoperator_subscription.suscription_statusColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setsuscription_statusNull() {
                this[this.tableoperator_subscription.suscription_statusColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isrenew_statusNull() {
                return this.IsNull(this.tableoperator_subscription.renew_statusColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setrenew_statusNull() {
                this[this.tableoperator_subscription.renew_statusColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Iscreated_onNull() {
                return this.IsNull(this.tableoperator_subscription.created_onColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setcreated_onNull() {
                this[this.tableoperator_subscription.created_onColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isoperator_idNull() {
                return this.IsNull(this.tableoperator_subscription.operator_idColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setoperator_idNull() {
                this[this.tableoperator_subscription.operator_idColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public class suscriptionRowChangeEvent : global::System.EventArgs {
            
            private suscriptionRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public suscriptionRowChangeEvent(suscriptionRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public suscriptionRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public class operator_subscriptionRowChangeEvent : global::System.EventArgs {
            
            private operator_subscriptionRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public operator_subscriptionRowChangeEvent(operator_subscriptionRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public operator_subscriptionRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591